"""Minimal PLY mesh reader.

Open3D is the project's point-cloud library (claude.md section 1) but it is a
heavy, GPU-adjacent dependency. Mock data generation and the CI dry-run must
work on a bare Python + numpy install, so loading is implemented here and
Open3D is used only where it earns its keep. Supports the two encodings trimesh
and most CAD exporters emit: ``binary_little_endian`` and ``ascii``.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np

from .geometry import scale_factor

_NUMPY_TYPES = {
    "char": "i1", "int8": "i1",
    "uchar": "u1", "uint8": "u1",
    "short": "i2", "int16": "i2",
    "ushort": "u2", "uint16": "u2",
    "int": "i4", "int32": "i4",
    "uint": "u4", "uint32": "u4",
    "float": "f4", "float32": "f4",
    "double": "f8", "float64": "f8",
}


@dataclass
class Mesh:
    """Triangle mesh in meters."""

    vertices: np.ndarray  # (V, 3) float64
    faces: np.ndarray  # (F, 3) int32
    face_colors: np.ndarray | None = None  # (F, 3) uint8
    name: str = ""

    @property
    def bounds(self) -> tuple[np.ndarray, np.ndarray]:
        return self.vertices.min(axis=0), self.vertices.max(axis=0)

    @property
    def extents(self) -> np.ndarray:
        lower, upper = self.bounds
        return upper - lower

    @property
    def centroid(self) -> np.ndarray:
        lower, upper = self.bounds
        return (lower + upper) / 2.0

    def centered(self) -> Mesh:
        """Copy with the axis-aligned bounding box centered on the origin.

        The model frame convention (ICD section 4) puts the part origin at the
        AABB center, so a pose refers to the block's geometric center.
        """
        return Mesh(self.vertices - self.centroid, self.faces, self.face_colors, self.name)

    def face_normals(self) -> np.ndarray:
        tri = self.vertices[self.faces]
        normals = np.cross(tri[:, 1] - tri[:, 0], tri[:, 2] - tri[:, 0])
        lengths = np.linalg.norm(normals, axis=1, keepdims=True)
        return normals / np.maximum(lengths, 1e-12)

    def sample_surface(self, count: int, seed: int = 0) -> np.ndarray:
        """Area-weighted uniform sample of ``count`` surface points.

        Used as the model point cloud for ICP registration.
        """
        rng = np.random.default_rng(seed)
        tri = self.vertices[self.faces]
        areas = 0.5 * np.linalg.norm(
            np.cross(tri[:, 1] - tri[:, 0], tri[:, 2] - tri[:, 0]), axis=1
        )
        total = float(areas.sum())
        if total <= 0.0:
            raise ValueError(f"mesh '{self.name}' has zero surface area")
        picks = rng.choice(len(areas), size=count, p=areas / total)
        # Uniform barycentric sampling within each picked triangle.
        u = rng.random((count, 1))
        v = rng.random((count, 1))
        flip = (u + v) > 1.0
        u[flip] = 1.0 - u[flip]
        v[flip] = 1.0 - v[flip]
        a, b, c = tri[picks, 0], tri[picks, 1], tri[picks, 2]
        return a + u * (b - a) + v * (c - a)


def save_ply(mesh: Mesh, path: str | Path, units: str = "m") -> Path:
    """Write a triangle mesh as an ASCII PLY.

    ASCII rather than binary: a reconstructed mesh is something a human will want
    to sanity-check in a text editor or diff, and these meshes are small.

    Args:
        mesh: vertices in meters.
        units: units to write in; ``"mm"`` divides by the mm scale factor.
    """
    file_path = Path(path)
    file_path.parent.mkdir(parents=True, exist_ok=True)

    vertices = np.asarray(mesh.vertices, dtype=np.float64) / scale_factor(units)
    faces = np.asarray(mesh.faces, dtype=np.int64)

    lines = [
        "ply",
        "format ascii 1.0",
        f"comment generated by roboworld_core.mesh_io (units: {units})",
        f"element vertex {len(vertices)}",
        "property float x",
        "property float y",
        "property float z",
        f"element face {len(faces)}",
        "property list uchar int vertex_indices",
        "end_header",
    ]
    lines.extend(f"{x:.6f} {y:.6f} {z:.6f}" for x, y, z in vertices)
    lines.extend(f"3 {a} {b} {c}" for a, b, c in faces)
    file_path.write_text("\n".join(lines) + "\n", encoding="ascii")
    return file_path


def _parse_header(raw: bytes) -> tuple[dict, int]:
    end = raw.find(b"end_header")
    if end < 0:
        raise ValueError("not a PLY file: 'end_header' missing")
    newline = raw.find(b"\n", end)
    header_text = raw[:newline].decode("ascii", errors="replace")
    offset = newline + 1

    fmt = None
    elements: list[dict] = []
    for line in header_text.splitlines():
        tokens = line.split()
        if not tokens:
            continue
        keyword = tokens[0]
        if keyword == "format":
            fmt = tokens[1]
        elif keyword == "element":
            elements.append({"name": tokens[1], "count": int(tokens[2]), "properties": []})
        elif keyword == "property" and elements:
            if tokens[1] == "list":
                elements[-1]["properties"].append(
                    {"list": True, "count_type": tokens[2], "item_type": tokens[3],
                     "name": tokens[4]}
                )
            else:
                elements[-1]["properties"].append(
                    {"list": False, "type": tokens[1], "name": tokens[2]}
                )
    if fmt is None:
        raise ValueError("PLY header has no 'format' line")
    return {"format": fmt, "elements": elements}, offset


def _read_binary(raw: bytes, offset: int, header: dict, little: bool) -> dict[str, dict]:
    prefix = "<" if little else ">"
    data: dict[str, dict] = {}
    for element in header["elements"]:
        count = element["count"]
        props = element["properties"]
        if not any(p["list"] for p in props):
            dtype = np.dtype([(p["name"], prefix + _NUMPY_TYPES[p["type"]]) for p in props])
            block = np.frombuffer(raw, dtype=dtype, count=count, offset=offset)
            offset += dtype.itemsize * count
            data[element["name"]] = {name: block[name] for name in dtype.names}
            continue

        # Mixed/list element (typically faces): parse row by row.
        columns: dict[str, list] = {p["name"]: [] for p in props}
        for _ in range(count):
            for prop in props:
                if prop["list"]:
                    count_dtype = np.dtype(prefix + _NUMPY_TYPES[prop["count_type"]])
                    n = int(np.frombuffer(raw, count_dtype, 1, offset)[0])
                    offset += count_dtype.itemsize
                    item_dtype = np.dtype(prefix + _NUMPY_TYPES[prop["item_type"]])
                    values = np.frombuffer(raw, item_dtype, n, offset)
                    offset += item_dtype.itemsize * n
                    columns[prop["name"]].append(np.array(values))
                else:
                    scalar_dtype = np.dtype(prefix + _NUMPY_TYPES[prop["type"]])
                    columns[prop["name"]].append(
                        np.frombuffer(raw, scalar_dtype, 1, offset)[0]
                    )
                    offset += scalar_dtype.itemsize
        data[element["name"]] = columns
    return data


def _read_ascii(raw: bytes, offset: int, header: dict) -> dict[str, dict]:
    lines = raw[offset:].decode("ascii", errors="replace").split("\n")
    cursor = 0
    data: dict[str, dict] = {}
    for element in header["elements"]:
        columns: dict[str, list] = {p["name"]: [] for p in element["properties"]}
        rows = 0
        while rows < element["count"]:
            line = lines[cursor].strip()
            cursor += 1
            if not line:
                continue
            tokens = line.split()
            index = 0
            for prop in element["properties"]:
                if prop["list"]:
                    n = int(float(tokens[index]))
                    index += 1
                    columns[prop["name"]].append(
                        np.array([int(float(t)) for t in tokens[index:index + n]])
                    )
                    index += n
                else:
                    columns[prop["name"]].append(float(tokens[index]))
                    index += 1
            rows += 1
        data[element["name"]] = columns
    return data


def load_ply(path: str | Path, units: str = "m", center: bool = True) -> Mesh:
    """Load a PLY triangle mesh and convert it to meters.

    Args:
        path: file to read.
        units: units the file is authored in; ``"mm"`` applies the documented
            mm -> m conversion (claude.md section 4).
        center: move the AABB center to the origin (model frame convention).
    """
    file_path = Path(path)
    raw = file_path.read_bytes()
    header, offset = _parse_header(raw)

    fmt = header["format"]
    if fmt == "ascii":
        parsed = _read_ascii(raw, offset, header)
    elif fmt in ("binary_little_endian", "binary_big_endian"):
        parsed = _read_binary(raw, offset, header, little=fmt.endswith("little_endian"))
    else:
        raise ValueError(f"unsupported PLY format '{fmt}' in {file_path}")

    if "vertex" not in parsed:
        raise ValueError(f"PLY has no vertex element: {file_path}")
    vertex = parsed["vertex"]
    vertices = np.stack(
        [np.asarray(vertex["x"], dtype=np.float64),
         np.asarray(vertex["y"], dtype=np.float64),
         np.asarray(vertex["z"], dtype=np.float64)],
        axis=1,
    ) * scale_factor(units)

    faces: list[list[int]] = []
    face_colors: list[tuple[int, int, int]] = []
    face_element = parsed.get("face", {})
    index_key = next(
        (k for k in ("vertex_indices", "vertex_index") if k in face_element), None
    )
    if index_key is not None:
        has_color = all(c in face_element for c in ("red", "green", "blue"))
        for i, indices in enumerate(face_element[index_key]):
            indices = np.asarray(indices, dtype=np.int64).ravel()
            # Fan-triangulate polygons so quads/n-gons survive the import.
            for k in range(1, len(indices) - 1):
                faces.append([int(indices[0]), int(indices[k]), int(indices[k + 1])])
                if has_color:
                    face_colors.append(
                        (int(face_element["red"][i]), int(face_element["green"][i]),
                         int(face_element["blue"][i]))
                    )
    if not faces:
        raise ValueError(f"PLY has no triangle faces: {file_path}")

    mesh = Mesh(
        vertices=vertices,
        faces=np.asarray(faces, dtype=np.int32),
        face_colors=np.asarray(face_colors, dtype=np.uint8) if face_colors else None,
        name=file_path.stem,
    )
    return mesh.centered() if center else mesh
